name: Playwright Tests

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.filter.outputs.diff }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      with:
        filters: |
          diff:
            - yarn.lock
            - '.github/**'
            - 'tests/**'
            - 'packages/**/src/**'

  e2e-tests:
    needs:
    - setup
    if: needs.setup.outputs.diff == 'true'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: yarn
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Download Build Artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: packages-build
        path: packages/
    - name: Install playwright browsers
      run: yarn playwright install --with-deps
    - name: Run tests
      run: yarn run test:e2e --shard=${SHARD}/${TOTAL}
      env:
        SHARD: ${{ matrix.shard }}
        TOTAL: ${{ strategy.job-total }}
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: playwright-report-${{ matrix.shard }}
        path: playwright-report
        retention-days: 30

  merge:
    runs-on: ubuntu-latest
    needs:
    - e2e-tests
    steps:
    - name: Merge Artifacts
      uses: actions/upload-artifact/merge@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: playwright-report
        pattern: playwright-report-*
