name: Main

env:
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - './package.json'
      - 'packages/**'
      - 'tests/**'
      - '.docker/**'

jobs:
  dispatch-updated-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Verify CHANGELOG Updates
        uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45.0.6
        id: changelog-updates
        with:
          since_last_remote_commit: true
          files: packages/orchestrator/*.md

      - name: Trigger 'micro-lc.github.io' Updates
        if: steps.changelog-updates.outputs.any_changed == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v70.1
        with:
          github-token: ${{ secrets.PAT_DOCS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'micro-lc.github.io',
              workflow_id: 'main.yml',
              ref: 'main'
            })

  prepare:
    uses: ./.github/workflows/prepare.yml

  checks:
    needs:
    - prepare
    uses: ./.github/workflows/checks.yml

  unit-tests:
    needs:
    - prepare
    uses: ./.github/workflows/unit-tests.yml

  e2e-tests:
    needs:
    - prepare
    uses: ./.github/workflows/e2e-tests.yml

  release-docker:
    needs:
    - checks
    - unit-tests
    - e2e-tests
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    uses: ./.github/workflows/release-docker.yml
    with:
      push: true
    secrets:
      docker_username: ${{ secrets.BOT_DOCKER_USERNAME }}
      docker_token: ${{ secrets.BOT_DOCKER_TOKEN }}
      nexus_username: ${{ secrets.NEXUS_USER }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}
      sysdig_token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
