name: Pull on Main

env:
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  checks:
    needs:
      - prepare
    uses: ./.github/workflows/checks.yml

  unit-tests:
    needs:
      - prepare
    uses: ./.github/workflows/unit-tests.yml

  e2e-tests:
    needs:
      - prepare
    uses: ./.github/workflows/e2e-tests.yml

  file-changes:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.filter.outputs.diff }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false

    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      with:
        filters: |
          diff:
            - '.docker/**'
            - '.github/**'

  test-docker:
    needs:
    - prepare
    - file-changes
    if: needs.file-changes.outputs.diff == 'true'
    uses: ./.github/workflows/release-docker.yml
    with:
      push: false
    secrets:
      docker_username: ${{ secrets.BOT_DOCKER_USERNAME }}
      docker_token: ${{ secrets.BOT_DOCKER_TOKEN }}
      nexus_username: ${{ secrets.NEXUS_USER }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}
      sysdig_token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
